training: False
name: "creation_annotation_and_dataset_config"
filterList:
  ["PrepareDatasetForPredictionFilter", "PredictionFilter", "ExtendAnnotationFilter", "CreateDatasetFilter"]
model_name: "Iteration_1_model"
